### ISSUE TITLE
Create function that converts a file path to the correct format (correct slashes) depending on OS (process.platform)

### ISSUE THREAD

**Issue by davideastmond** [davideastmond/easy-weather#10]
#### Problem

**[Basic JavaScript - string manipulation]** 
Due to easy-weather being developed as a cross-platform app, file paths for Windows and macOS use different slash directions (ie. "\\" or "/").

#### Task
Create a function whose input is an OS (based on process.platform) and a path string and return the correctly formatted file path for the current OS.

#### Sample input: 
`getCorrectlyFormattedFilePath("darwin", "path\\myPath\\file.txt")`

#### Sample output:
`path/myPath/file.txt`

#### Testing
Write a test for this function to test different types of inputs and OS environments and ensure the output is correct.

**Comment by Serhazor** [comment]
function convertPath(){
      var oldPath = userInput;
      var newPath = oldPath.replace('\', '/');

      console.log(newPath);
};


convertPath();

**Comment by davideastmond** [comment]
> ```
> function convertPath(){
>       var oldPath = userInput;
>       var newPath = oldPath.replace('\', '/');
> 
>       console.log(newPath);
> };
> 
> 
> convertPath();
> ```

Nice start. How is the function going to know about the user's input and the operating system?
